# Generated by Django 5.2.13 on 2026-04-18 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tyresize',
            name='company',
            field=models.CharField(blank=True, help_text='Tyre company/brand', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tyresize',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tyresize',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tyresize',
            name='remoulding_type',
            field=models.CharField(choices=[('hot', 'Hot'), ('cold', 'Cold')], default='hot', max_length=10),
        ),
        migrations.AddField(
            model_name='tyresize',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='tyresize',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rate/Price for remoulding', max_digits=10),
        ),
        migrations.CreateModel(
            name='TyreNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre_number', models.CharField(help_text='Individual tyre number/serial number', max_length=100)),
                ('status', models.CharField(choices=[('received', 'Received'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered')], default='received', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remoulding_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyre_numbers', to='tyres.remouldingjob')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('remoulding_job', 'tyre_number')},
            },
        ),
    ]
