# Generated by Django 5.2.13 on 2026-05-17 14:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tyres', '0002_tyresize_company_tyresize_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tyresize',
            options={'ordering': ['vehicle_category', 'size']},
        ),
        migrations.RenameField(
            model_name='remouldingjob',
            old_name='total_cost',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='remouldingjob',
            name='date_entered',
        ),
        # Add vehicle_category BEFORE AlterUniqueTogether which references it
        migrations.AddField(
            model_name='tyresize',
            name='vehicle_category',
            field=models.CharField(choices=[('tractor', 'Tractor'), ('earth_mover', 'Earth Mover'), ('truck', 'Truck'), ('truck_bus_tubeless', 'Truck/Bus Tubeless'), ('tempo', 'Tempo'), ('mini_truck', 'Mini Truck')], default='truck', max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='tyresize',
            unique_together={('size', 'vehicle_category')},
        ),
        migrations.AddField(
            model_name='remouldingjob',
            name='cuts_repairs',
            field=models.TextField(blank=True, default='', help_text='Notes on cuts, repairs, or damage'),
        ),
        migrations.AddField(
            model_name='remouldingjob',
            name='in_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='remouldingjob',
            name='remoulding_sub_type',
            field=models.CharField(choices=[('rib', 'Rib'), ('lug', 'Lug'), ('mixed', 'Mixed'), ('highway', 'Highway'), ('hot', 'Hot'), ('cold', 'Cold')], default='rib', max_length=20),
        ),
        migrations.AddField(
            model_name='remouldingjob',
            name='remoulding_type',
            field=models.CharField(choices=[('pre_cure', 'Pre-cure'), ('mold_cure', 'Mold-cure')], default='pre_cure', max_length=20),
        ),
        migrations.AddField(
            model_name='remouldingjob',
            name='tyre_brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='remouldingjob',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed'), ('delivered', 'Delivered')], default='in_progress', max_length=20),
        ),
        migrations.AlterField(
            model_name='tyrenumber',
            name='tyre_number',
            field=models.CharField(help_text='Individual tyre serial number', max_length=100),
        ),
        migrations.AlterField(
            model_name='tyresize',
            name='size',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='tyresize',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tyresize',
            name='price',
        ),
        migrations.RemoveField(
            model_name='tyresize',
            name='remoulding_type',
        ),
        migrations.CreateModel(
            name='RateCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tyre_brand', models.CharField(max_length=100)),
                ('remoulding_type', models.CharField(choices=[('pre_cure', 'Pre-cure'), ('mold_cure', 'Mold-cure')], max_length=20)),
                ('remoulding_sub_type', models.CharField(choices=[('rib', 'Rib'), ('lug', 'Lug'), ('mixed', 'Mixed'), ('highway', 'Highway'), ('hot', 'Hot'), ('cold', 'Cold')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tyre_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_cards', to='tyres.tyresize')),
            ],
            options={
                'ordering': ['tyre_brand', 'remoulding_type', 'tyre_size'],
                'unique_together': {('tyre_brand', 'remoulding_type', 'remoulding_sub_type', 'tyre_size')},
            },
        ),
    ]
